### ISSUE TITLE
Need more details about setting up and running Care

### ISSUE THREAD

**Issue by realtimclemans** [openlattice/care#1021]
On a Mac with Webpack installed by Brew and running `npm install` I'm getting errors. Please add more details for getting Care running.

```
npm run app

> care@0.0.0 app
> webpack serve --config config/webpack/webpack.config.app.js --env development

ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /care/
ℹ ｢wds｣: Content not from webpack is served from /Users/tim/Desktop/code/care/build
ℹ ｢wds｣: 404s will fallback to /care/
✖ ｢wdm｣: ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/pro-regular-svg-icons/faCampground' in '/Users/tim/Desktop/code/care/src/containers/app'
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/Compilation.js:1762:28
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/tim/Desktop/code/care/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/tim/Desktop/code/care/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/tim/Desktop/code/care/node_modules/webpack/lib/NormalModuleFactory.js:920:5
✖ ｢wdm｣: resolve '@fortawesome/pro-regular-svg-icons/faCampground' in '/Users/tim/Desktop/code/care/src/containers/app'
  Cache miss
    Parsed request is a module
    using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./src/containers/app)
      Field 'browser' doesn't contain a valid alias configuration
      resolve as module
        looking for modules in /Users/tim/Desktop/code/care/src
          /Users/tim/Desktop/code/care/src/@fortawesome/pro-regular-svg-icons doesn't exist
        looking for modules in /Users/tim/Desktop/code/care/node_modules
          existing directory /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons
            using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./node_modules/@fortawesome/pro-regular-svg-icons)
              using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./node_modules/@fortawesome/pro-regular-svg-icons/faCampground)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground.js doesn't exist
                .css
                  Field 'browser' doesn't contain a valid alias configuration
                  /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground.css doesn't exist
                as directory
                  /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground doesn't exist
  Parsed request is a module
  using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./src/containers/app)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/tim/Desktop/code/care/src
        /Users/tim/Desktop/code/care/src/@fortawesome/pro-regular-svg-icons doesn't exist
      looking for modules in /Users/tim/Desktop/code/care/node_modules
        existing directory /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons
          using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./node_modules/@fortawesome/pro-regular-svg-icons)
            using description file: /Users/tim/Desktop/code/care/package.json (relative path: ./node_modules/@fortawesome/pro-regular-svg-icons/faCampground)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground.js doesn't exist
              .css
                Field 'browser' doesn't contain a valid alias configuration
                /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground.css doesn't exist
              as directory
                /Users/tim/Desktop/code/care/node_modules/@fortawesome/pro-regular-svg-icons/faCampground doesn't exist
```

**Comment by solomontang** [comment]
Hi Tim,

This repo uses font-awesome pro icons and requires the appropriate license. If you're still interested in running the application for yourself, feel free to fork the repo and replace the pro icons with the free versions. Otherwise, checkout font-awesome's website on how to obtain and utilize a pro license

https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro
